# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_pb2 as books__pb2


class BookServiceStub(object):
    """The book service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAll = channel.unary_unary(
                '/books.BookService/GetAll',
                request_serializer=books__pb2.GetAllRequest.SerializeToString,
                response_deserializer=books__pb2.GetAllResponse.FromString,
                )
        self.GetOne = channel.unary_unary(
                '/books.BookService/GetOne',
                request_serializer=books__pb2.GetOneRequest.SerializeToString,
                response_deserializer=books__pb2.GetOneResponse.FromString,
                )
        self.PostOne = channel.unary_unary(
                '/books.BookService/PostOne',
                request_serializer=books__pb2.PostOneRequest.SerializeToString,
                response_deserializer=books__pb2.PostOneResponse.FromString,
                )
        self.PostList = channel.unary_unary(
                '/books.BookService/PostList',
                request_serializer=books__pb2.PostListRequest.SerializeToString,
                response_deserializer=books__pb2.PostListResponse.FromString,
                )


class BookServiceServicer(object):
    """The book service definition.
    """

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=books__pb2.GetAllRequest.FromString,
                    response_serializer=books__pb2.GetAllResponse.SerializeToString,
            ),
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=books__pb2.GetOneRequest.FromString,
                    response_serializer=books__pb2.GetOneResponse.SerializeToString,
            ),
            'PostOne': grpc.unary_unary_rpc_method_handler(
                    servicer.PostOne,
                    request_deserializer=books__pb2.PostOneRequest.FromString,
                    response_serializer=books__pb2.PostOneResponse.SerializeToString,
            ),
            'PostList': grpc.unary_unary_rpc_method_handler(
                    servicer.PostList,
                    request_deserializer=books__pb2.PostListRequest.FromString,
                    response_serializer=books__pb2.PostListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """The book service definition.
    """

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BookService/GetAll',
            books__pb2.GetAllRequest.SerializeToString,
            books__pb2.GetAllResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BookService/GetOne',
            books__pb2.GetOneRequest.SerializeToString,
            books__pb2.GetOneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BookService/PostOne',
            books__pb2.PostOneRequest.SerializeToString,
            books__pb2.PostOneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BookService/PostList',
            books__pb2.PostListRequest.SerializeToString,
            books__pb2.PostListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
