# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x05\x62ooks\"c\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\t\"\x0f\n\rGetAllRequest\",\n\x0eGetAllResponse\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book\"\x1b\n\rGetOneRequest\x12\n\n\x02id\x18\x01 \x01(\t\"+\n\x0eGetOneResponse\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\"+\n\x0ePostOneRequest\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\",\n\x0fPostOneResponse\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\"-\n\x0fPostListRequest\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book\".\n\x10PostListResponse\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book2\xf2\x01\n\x0b\x42ookService\x12\x35\n\x06GetAll\x12\x14.books.GetAllRequest\x1a\x15.books.GetAllResponse\x12\x35\n\x06GetOne\x12\x14.books.GetOneRequest\x1a\x15.books.GetOneResponse\x12\x38\n\x07PostOne\x12\x15.books.PostOneRequest\x1a\x16.books.PostOneResponse\x12;\n\x08PostList\x12\x16.books.PostListRequest\x1a\x17.books.PostListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOK']._serialized_start=22
  _globals['_BOOK']._serialized_end=121
  _globals['_GETALLREQUEST']._serialized_start=123
  _globals['_GETALLREQUEST']._serialized_end=138
  _globals['_GETALLRESPONSE']._serialized_start=140
  _globals['_GETALLRESPONSE']._serialized_end=184
  _globals['_GETONEREQUEST']._serialized_start=186
  _globals['_GETONEREQUEST']._serialized_end=213
  _globals['_GETONERESPONSE']._serialized_start=215
  _globals['_GETONERESPONSE']._serialized_end=258
  _globals['_POSTONEREQUEST']._serialized_start=260
  _globals['_POSTONEREQUEST']._serialized_end=303
  _globals['_POSTONERESPONSE']._serialized_start=305
  _globals['_POSTONERESPONSE']._serialized_end=349
  _globals['_POSTLISTREQUEST']._serialized_start=351
  _globals['_POSTLISTREQUEST']._serialized_end=396
  _globals['_POSTLISTRESPONSE']._serialized_start=398
  _globals['_POSTLISTRESPONSE']._serialized_end=444
  _globals['_BOOKSERVICE']._serialized_start=447
  _globals['_BOOKSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
